name: "Lint PR Title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          # Define the exact list of allowed types.
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
